breakdown_search/urls.py
from django.conf.urls import url

from breakdown_search.views import BreakdownSearch, TreeSearch, GetPrevNode, GetInstruction, GetRootNode

urlpatterns = [
    url(r'^breakdown_search/$', BreakdownSearch.as_view(), name='breakdown_search'),
    url(r'^search/$', TreeSearch.as_view(), name='search'),
    url(r'^go_back/$', GetPrevNode.as_view(), name='prev_node'),
    url(r'^instruction/$', GetInstruction.as_view(), name='instruction'),
    url(r'^root_node/$', GetRootNode.as_view(), name='root_node')
]

cars/urls.py
from django.conf.urls import url

from cars.views import BreakdownSearch, AjaxCarsModels, AjaxCarsModifications, AjaxBreakdowns, AjaxCarsYears, \
    AjaxBreakdown

urlpatterns = [
    url(r'^breakdown_search/$', BreakdownSearch.as_view(), name='breakdown_search'),
    url(r'^get_models/$', AjaxCarsModels.as_view(), name='cars_models'),
    url(r'^get_years/$', AjaxCarsYears.as_view(), name='cars_years'),
    url(r'^get_modifications/$', AjaxCarsModifications.as_view(), name='cars_modifications'),
    url(r'^breakdowns/$', AjaxBreakdowns.as_view(), name='breakdowns'),
    url(r'^breakdown/$', AjaxBreakdown.as_view(), name='breakdown')
]

vsepolomki/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^cars/', include('cars.urls', namespace='cars')),
    url(r'^breakdown_search/', include('breakdown_search.urls', namespace='breakdown'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breakdown_search/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models


class Node(models.Model):
    car_model = models.ForeignKey("cars.CarModel", null=True, blank=True, verbose_name=u'Модель машины, на которую завязана нода')
    answer_text = models.CharField(max_length=250, blank=True, verbose_name=u'Текст на кнопке ответа у родительской ноды')
    name = models.CharField(max_length=200, blank=True, verbose_name=u'Название ноды')
    node_text = models.TextField(max_length=1000, blank=True, verbose_name=u'Описание ноды')
    root_nodes = models.ManyToManyField("self", blank=True, symmetrical=False)
    instruction = models.ForeignKey("InstructionStep", null=True, blank=True, verbose_name=u'Первый шаг инструкции')
    root = models.BooleanField(default=False, verbose_name=u'Корневая ли нода')
    breakdowns = models.ManyToManyField("cars.Breakdown", blank=True, verbose_name=u'Список возможных поломог')
    mileage = models.IntegerField(default=0, verbose_name=u'Показывать ноду, если пробег больше')
    low_mileage = models.IntegerField(default=10000000, verbose_name=u'Показывать ноду, если пробег меньше')
    need_select = models.BooleanField(default=False, verbose_name=u'Использовать для ответов в верстке селект')

    def __unicode__(self):
        return self.name + ' ' + self.node_text

    def as_dict(self, mileage=1000000):
        return {
            'id': self.id,
            'answer_text': self.answer_text,
            'name': self.name,
            'node_text': self.node_text,
            'root': self.root,
            'instruction': self.instruction.id if self.instruction else None,
            'mileage': self.mileage,
            'need_select': self.need_select,
            'breakdowns': [breakdown.as_dict() for breakdown in self.breakdowns.all().filter(mileage__lte=mileage)] if self.breakdowns else None
        }


class InstructionStep(models.Model):
    text = models.TextField(max_length=1000, blank=True)
    next_step = models.OneToOneField("self", null=True, blank=True)
    img = models.ImageField(blank=True, null=True)

    def __unicode__(self):
        return self.text

    def as_dict(self):
        return {
            'text': self.text,
            'img': self.img.url if self.img else None
        }

breakdown_search/views.py
from django.http import HttpResponseBadRequest, JsonResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from breakdown_search.models import Node, InstructionStep
from cars.models import CarBrand


class BreakdownSearch(TemplateView):
    template_name = 'breakdown_search_alg.html'

    def get_context_data(self, **kwargs):
        context = {
            'cars_brands': CarBrand.objects.all()
        }
        return context


class GetRootNode(View):
    def get(self, request):
        try:
            model_id = int(request.GET.get('model'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        node = get_object_or_404(Node, root=True, car_model=model_id)
        request.session['history'] = [node.id]
        return JsonResponse({
            'node': node.as_dict(),
            'answers': [{'id': answer.id, 'text': answer.answer_text} for answer in node.node_set.all()]
        })


class TreeSearch(View):
    def get(self, request):
        try:
            node_id = int(request.GET.get('node_id'))
            node = get_object_or_404(Node, id=node_id)
            root_node = int(request.GET.get('root_node', 0))
            mileage = int(request.GET.get('mileage', 9999999))
            if mileage == 0:
                mileage = 9999999
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        l = request.session['history']
        l.append(node.id)
        request.session['history'] = l
        context = {'node': node.as_dict(mileage=mileage),
                   'answers': [{'id': answer.id, 'text': answer.answer_text} for answer in node.node_set.all() if answer.mileage <= mileage and answer.low_mileage >= mileage],
                   'root_node': root_node}
        return JsonResponse(context)


class GetPrevNode(View):
    def get(self, request):
        try:
            mileage = request.GET.get('mileage', 9999999)
            if mileage:
                mileage = int(request.GET.get('mileage', 9999999))
            else:
                mileage = 9999999
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        l = request.session['history']
        l.pop()
        node = get_object_or_404(Node, id=l[-1])
        request.session['history'] = l
        if not node:
            return Http404()
        context = {'node': node.as_dict(),
                   'answers': [{'id': answer.id, 'text': answer.answer_text} for answer in node.node_set.all() if answer.mileage <= mileage and answer.low_mileage >= mileage]}
        return JsonResponse(context)


class GetInstruction(View):
    def get(self, request):
        try:
            step_id = int(request.GET.get('step_id'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        step = get_object_or_404(InstructionStep, id=step_id)
        steps = [step.as_dict()]
        while step.next_step:
            step = step.next_step
            steps.append(step.as_dict())
        return JsonResponse({'steps': steps})

breakdown_search/templates/breakdown_search_alg.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top:100px;min-height:600px;">
        <ul class="nav nav-tabs" role="tablist" id="Tab1">
            <li class="tab-0 active"><a href="#St1" role="tab" data-toggle="tab">Шаг 1.</a></li>
            <li class="tab-1" style="display: none"><a href="#St2" role="tab" data-toggle="tab">Шаг 2.</a></li>
            <li class="tab-2" style="display: none"><a href="#St3" role="tab" data-toggle="tab">Шаг 3.</a></li>
        </ul>
    <div class="tab-content" >
        <div class="tab-pane active" id="St1" >
            {% include 'tabs/car_select_tab.html' %}
        </div>
        <div class="tab-pane" id="St2">
            {% include 'tabs/tree_tab.html' %}
        </div>
        <div class="tab-pane " id="St3">
            {% include 'tabs/service_select_tab.html' %}
        </div>
    </div>
</div>
    <script>
    $(document).ready(function () {
        var questionRowTemplate =
            _.template('<div class="row"> \
                <article class="col-md-9 maincontent">\
                    <% if (!node.need_select) { %>\
                    <a class="return-back btn btn-warning" href="<%= node.id %>" style="background-color: #888888">Назад</a>\
                    <br />\
                    <header class="page-header" style="margin-top:0px"><br>\
                        <h1 style="margin-top:0px;font-family: \'jura\'"><b><%= node.name %></b></h1>\
                        <h3 class="page-title" style="font-family: \'jura\'"><%= node.node_text %></h3>\
                    </header>\
                    <% _.each(answers, function(answer) { %> \
                     <a class="btn btn-action btn-lg answer" style="margin: 1%;" href="<%= answer.id %>"><%= answer.text %></a>\
                     <% }); %>\
                    <%} else { %>\
                      <% if (!node.root) { %>\
                      <a class="return-back btn btn-warning" href="<%= node.id %>" style="background-color: #888888">Назад</a>\
                      <% } %>\
                     <header class="page-header" style="margin-top:0px"><br>\
                        <h3 style="margin-top:0px;font-family: \'jura\'"><b><%= node.name %></b></h1>\
                        <h1 class="page-title" style="font-family: \'jura\'"><%= node.node_text %></h3>\
                        <select class="branch-select form-control" style="height: 45px; width: 190px; margin:10px">\
                        <option value=""> ----- </option>\
                    <% _.each(answers, function(answer) { %>\
                        <option value="<%= answer.id %>"> <%= answer.text %> </option>\
                    <% }) %>\
                    </select>\
                    </header>\
                    <% } %>\
                </article>\
            </div>');

        var breakdownTemplate = _.template('<div class="row"> \
                <article class="col-md-9 maincontent">\
                <% if (!node.root) { %>\
                    <a class="return-back btn btn-warning" href="<%= node.id %>" style="background-color: #888888">Назад</a>\
                    <%}%>\
                    <br /><br /><br />\
                    <% _.each(node.breakdowns, function(breakdown, index) { %>\
                    <div class="well">\
                    <header class="page-header" style="margin-top:0px"><br>\
                        <h1 style="margin-top:0px;font-family: \'jura\'"><b>Возможная поломка <%= index+1 %></b></h1>\
                        <h2 class="page-title" style="font-family: \'jura\'"><%= breakdown.name %></h2>\
                    </header>\
                    <a class="btn btn-success btn-lg breakdown-show" style="margin: 1%;" href="<%= breakdown.id %>">Просмотреть</a>\
                    </div>\
                    <% }) %>\
                </article>\
            </div>');

        var instructionTemplate = _.template(
                '<% _.each(steps, function(step) { %> ' +
                '<div class="thumbnail well" style="font-size: 16pt">' +
                        '<div class="caption">'+
                        '<p><%= step.text %></p>'+
                    '</div>'+
                 '<% if (step.img) { %>' +
                   '<img src="<%= step.img %>" >'+
                   '<% } %>'+
                '</div> <% }) %>');

        var questionDest = $('.question-class');
        var instructionDiv = $('.instructions');
        var instructionDest = $('.instruction-dest');


        $('body').on('click', 'a.breakdown-show', function (event) {
            event.preventDefault();
            tab2.show();
            $('.nav-tabs li:eq(2) a').tab('show');
            var id = Number($(this).attr('href'));
            if (!isNaN(id)) {
                var breakdownDescription = $('.breakdown-description');
                var breakdownName = $('.breakdown-name');
                var symptoms = $('.symptoms');
                var services = $('.services');
                var breakdownDescriptionTemplate = _.template("<td class='tab1' data-label='Сложность'><%= difficulty %></td> \
                                                  <td class='tab1'  data-label='Вид работ'><%= jobs_types %></td> \
                                                  <% if (show_services) { %><td class='tab1' data-label='Необходимые запчасти'><%= spares %></td> \
                                                  <td class='tab1' data-label='Стоимость ремонта в техцентре'><%= price %></td> <% } %>");
                var serviceTemplate = _.template("<tr><td><%= name %></td> \
                                       <td><%= address %></td>\
                                       <td><a href='http://<%= site %>'><%= site %></td>\
                                       <td><%= price %></td></tr>");
                $.get(
                    '{% url 'cars:breakdown' %}',
                        {
                            breakdown_id: id,
                            brand: $('.brand-select').val()
                        }
                ).done(function (data) {
                    breakdownDescription.html(breakdownDescriptionTemplate(data.breakdown));
                    breakdownName.html(data.breakdown.name);
                    var servicesDest = $('.services-dest');
                    var symptomsDest = $('.symptoms-dest');

                    if (data.breakdown.show_services){
                        symptomsDest.show();
                        symptoms.html(data.breakdown.symptoms);
                        var servicesResult = '';
                        if (myMap) {
                            myMap.geoObjects.removeAll();

                            _.each(data.services, function (service) {
                                myMap.geoObjects.add(new ymaps.Placemark([service.longitude, service.latitude], {
                                        balloonContent: '<strong>' + service.name + '</strong> <br/>' + service.address + '<br /> <a href="'+ service.site +'">'+ service.site +'</a>'
                                    }, {
                                        preset: 'islands#dotIcon',
                                        iconColor: '#735184'
                                    })
                                );
                                servicesResult += serviceTemplate(service);
                            });
                        } else {
                            _.each(data.services, function (service) {
                                servicesResult += serviceTemplate(service);
                            });
                        }
                        servicesDest.show();
                        services.html(servicesResult);
                    } else {
                        servicesDest.hide();
                        symptomsDest.hide();
                    }

                });
            }
        });

        $('body').on('click', 'a.answer', function (event) {
            event.preventDefault();
            var href = $(this).attr('href');
            $.get('{% url 'breakdown:search' %}', {
                node_id: Number(href),
                mileage: Number($('.mileage').val())
            }).done(function (data) {
                if (data.node.instruction) {
                    $.get('{% url 'breakdown:instruction' %}', {
                        step_id: Number(data.node.instruction)
                    }).done(function (data) {
                        instructionDiv.show();
                        instructionDest.html(instructionTemplate(data));
                        console.log(instructionTemplate(data))
                    })
                } else {
                    instructionDiv.hide();
                }
                if (data.answers.length != 0) {
                    questionDest.html(questionRowTemplate(data));
                } else {
                    questionDest.html(breakdownTemplate(data));

                }
            })
        });
        $('body').on('click', 'a.return-back', function(event){
            event.preventDefault();
            var href = $(this).attr('href');
            $.get('{% url 'breakdown:prev_node' %}', {mileage: $('.mileage').val()}).done(function (data) {
                 if (data.node.instruction) {
                    $.get('{% url 'breakdown:instruction' %}', {
                        step_id: Number(data.node.instruction)
                    }).done(function (data) {
                        instructionDiv.show();
                        instructionDest.html(instructionTemplate(data));
                    })
                } else {
                    instructionDiv.hide();
                }
                questionDest.html(questionRowTemplate(data));

            });
        });

        $('body').on('change', 'select.branch-select', function (event) {
{#            alert($('.mileage').val())#}
            var href = $(this).val();
            $.get('{% url 'breakdown:search' %}', {
                node_id: Number(href),
                mileage: Number($('.mileage').val())
            }).done(function (data) {
                if (data.node.instruction) {
                    $.get('{% url 'breakdown:instruction' %}', {
                        step_id: Number(data.node.instruction)
                    }).done(function (data) {
                        instructionDiv.show();
                        instructionDest.html(instructionTemplate(data));
                        console.log(instructionTemplate(data))
                    })
                } else {
                    instructionDiv.hide();
                }
                if (data.answers.length != 0) {
                    questionDest.html(questionRowTemplate(data));
                } else {
                    questionDest.html(breakdownTemplate(data));

                }
            })
        });

        var tab0 = $('.tab-0');
            var tab1 = $('.tab-1');
            var tab2 = $('.tab-2');
            $(".btn-car").click(function (event) {
                event.preventDefault();
                tab1.show();
                $(".nav-tabs li:eq(1) a").tab('show');
                $.get('{% url 'breakdown:root_node' %}', {
                    model: $('.model-select').val()
                }).done(function (data) {
                    questionDest.html(questionRowTemplate(data));
                    instructionDiv.hide();
                });
            });
            tab0.click(function () {
                tab1.hide();
                tab2.hide();
            });
            tab1.click(function () {
               tab2.hide();
            })




    });
    </script>
    <script type="text/javascript" src="{% static 'cars/js/ajaxloads.js' %}"></script>
{% endblock %}