cars/urls.py
from django.conf.urls import url

from cars.views import BreakdownSearch, AjaxCarsModels, AjaxCarsModifications, AjaxBreakdowns, AjaxCarsYears, \
    AjaxBreakdown

urlpatterns = [
    url(r'^breakdown_search/$', BreakdownSearch.as_view(), name='breakdown_search'),
    url(r'^get_models/$', AjaxCarsModels.as_view(), name='cars_models'),
    url(r'^get_years/$', AjaxCarsYears.as_view(), name='cars_years'),
    url(r'^get_modifications/$', AjaxCarsModifications.as_view(), name='cars_modifications'),
    url(r'^breakdowns/$', AjaxBreakdowns.as_view(), name='breakdowns'),
    url(r'^breakdown/$', AjaxBreakdown.as_view(), name='breakdown')
]

vsepolomki/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^cars/', include('cars.urls', namespace='cars')),
    url(r'^breakdown_search/', include('breakdown_search.urls', namespace='breakdown'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.db.models import Max, Min
from django.utils import timezone


class CarBrand(models.Model):
    class Meta:
        verbose_name_plural = u'Марки машин'
        verbose_name = u'Марки машины'

    name = models.CharField(max_length=100, verbose_name=u'Название марки')

    def __unicode__(self):
        return self.name


class CarModel(models.Model):
    class Meta:
        verbose_name_plural = u'Модели машиин'
        verbose_name = u'Модель машины'

    name = models.CharField(max_length=100, verbose_name=u'Название модели машины')
    brand = models.ForeignKey('CarBrand', verbose_name=u'Марка машины')

    def __unicode__(self):
        return self.brand.__unicode__() + ' ' + self.name


class CarModification(models.Model):
    class Meta:
        verbose_name_plural = u'Модификации машин'
        verbose_name = u'Модификация машины'

    ENGINE_TYPES = (
        (0, 'gasoline'),
        (1, 'diesel'),
        (2, 'hybrid'),
        (3, 'electric'),
    )

    TRANSMISSION_TYPES = (
        (0, 'MT'),
        (1, 'AT'),
        (2, 'AMT'),
        (3, 'CVT')
    )

    DRIVE_TYPES = (
        (0, 'front'),
        (1, 'rear',),
        (2, 'all')
    )

    YEARS = ((i, i) for i in range(1950, timezone.now().year + 1))

    car_model = models.ForeignKey('CarModel', verbose_name=u'Модель машины')
    engine_type = models.IntegerField(choices=ENGINE_TYPES, default=0, verbose_name=u'Тип двигателя')
    transmission_type = models.IntegerField(choices=TRANSMISSION_TYPES, default=0, verbose_name=u'Тип трансмиссии')
    engine_volume = models.IntegerField(verbose_name=u'Объем двигателя', null=True, blank=True)
    horsepower = models.IntegerField(verbose_name=u'Лошадиные силы', null=True, blank=True)
    drive = models.IntegerField(choices=DRIVE_TYPES, default=0, verbose_name=u'Тип привода')
    year_from = models.IntegerField(choices=YEARS, verbose_name=u'С какого года', null=True)
    year_to = models.IntegerField(choices=YEARS, verbose_name=u'По какой год', null=True)

    def __unicode__(self):
        return self.car_model.__unicode__() + ' ' + self.get_engine_type_display() + ' ' + str(self.engine_volume) + ' ' + self.get_transmission_type_display()


class BreakdownType(models.Model):
    class Meta:
        verbose_name_plural = u'Типы поломок'
        verbose_name = u'Тип поломки'

    name = models.CharField(max_length=100, verbose_name=u'Тип поломки')

    def __unicode__(self):
        return self.name


class Breakdown(models.Model):
    class Meta:
        verbose_name_plural = u'Поломки'
        verbose_name = u'Поломка'

    DIFFICULTIES = (
        (0, u'Легко'),
        (1, u'Средне'),
        (2, u'Сложно')
    )

    breakdown_type = models.ForeignKey('BreakdownType', verbose_name=u'Тип поломки', null=True)
    name = models.CharField(max_length=100, verbose_name=u'Название поломки', blank=True)
    difficulty = models.IntegerField(choices=DIFFICULTIES, default=0, verbose_name=u'Сложность поломки')
    jobs_types = models.TextField(max_length=1000, blank=True, verbose_name=u'Виды работ')
    spares = models.TextField(max_length=250, blank=True, verbose_name=u'Запчасти')
    symptoms = models.TextField(max_length=1000, blank=True, verbose_name=u'Симптомы')
    show_services = models.BooleanField(default=True, verbose_name=u'Показывать автосервисы')
    mileage = models.IntegerField(default=0, verbose_name=u'не показываеть, если пробег меньше')

    def __unicode__(self):
        return self.name

    def as_dict(self, price=False, brand_id=None):
        from services.models import Work
        dict = {
            'id': self.id,
            'name': self.name,
            'difficulty': self.get_difficulty_display(),
            'jobs_types': self.jobs_types,
            'spares': self.spares,
            'symptoms': self.symptoms,
            'show_services': self.show_services,
        }
        if price:
            min_max_dict = Work.objects.filter(breakdown=self, brand_id=brand_id).aggregate(min=Min('price'), max=Max('price'))
            dict.update({
                'price': str(min_max_dict['min']) + '-' + str(min_max_dict['max'])
            })
        return dict

cars/views.py
from itertools import groupby

from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from itertools import chain
# Create your views here.
from django.views.generic import TemplateView, View
from cars.models import CarBrand, CarModel, CarModification, BreakdownType, Breakdown
from services.models import Service, Work

class BreakdownSearch(TemplateView):
    template_name = 'breakdown_search.html'

    def get_context_data(self, **kwargs):
        context = super(BreakdownSearch, self).get_context_data(**kwargs)
        context['cars_brands'] = CarBrand.objects.all()
        return context


class AjaxCarsModels(View):
    def get(self, request):
        try:
            brand_id = int(request.GET.get('brand_id'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        models = CarModel.objects.filter(brand_id=brand_id)
        return JsonResponse({"models": [{"id": model.id, "name": model.name} for model in models]})


class AjaxCarsYears(View):
    def get(self,  request):
        try:
            model_id = int(request.GET.get('model_id'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        cms = CarModification.objects.filter(car_model_id=model_id)
        intervals = [(cm.year_from, cm.year_to + 1) for cm in cms]
        years_list = chain.from_iterable([[i for i in range(*interval)] for interval in intervals])
        return JsonResponse({
            "years": sorted(set(years_list))
        })


class AjaxCarsModifications(View):
    def get(self, request):
        try:
            model_id = int(request.GET.get('model_id'))
            year = int(request.GET.get('year'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        modifications = CarModification.objects.filter(car_model_id=model_id, year_from__lte=year, year_to__gte=year)
        return JsonResponse({"modifications": [{"id": modification.id, "name": modification.__unicode__()} for modification in modifications]})


class AjaxBreakdowns(View):
    def get(self, request):
        context = {'breakdowns': []}
        breakdowns = Breakdown.objects.filter(show_services=True).select_related('breakdown_type').order_by('breakdown_type')
        for k, group in groupby(breakdowns, lambda x: x.breakdown_type):
            breakdown = {
                'text': k.name,
                'nodes': []
            }
            for g in group:
                breakdown['nodes'].append({
                    'text': g.name,
                    'href': '#' + str(g.id)
                })
            context['breakdowns'].append(breakdown)
        return JsonResponse(context)


class AjaxBreakdown(View):
    def get(self, request):
        try:
            breakdown_id = int(request.GET.get('breakdown_id'))
            brand = int(request.GET.get('brand'))
        except (ValueError, TypeError):
            return HttpResponseBadRequest()
        breakdown = get_object_or_404(Breakdown, id=breakdown_id)
        services_list = Work.objects.filter(breakdown_id=breakdown_id).values_list('service', flat=True)
        services = Service.objects.filter(id__in=services_list, work__brand=brand, work__breakdown_id=breakdown_id)
        services = [service.as_dict(breakdown.id) for service in services]
        context = {'breakdown': breakdown.as_dict(price=True, brand_id=brand), 'services': services}
        return JsonResponse(context)

cars/templates/tabs/breakdown_select_tab.html
<div class="row">
    <article class="col-md-9 maincontent">
        <header class="page-header">
            <h4 class="page-title" style="font-size:30px" >Двигаемся дальше!</h4>
            <h5 class="page-title" style="font-size:24px">Теперь нужно выбрать, в чем неисправность.</h5>
        </header>
        <div id="treeview12" class="treeview col-md-9">
        </div>
        <br />
        <a class="btn btn-default btn-general" role="button" style="margin: 1%;padding:15px 10px 15px 10px;" href="{% url 'breakdown:breakdown_search' %}">Я не знаю в чем конкретно неисправность.</a>
        <a class="btn btn-action btn-general btn-breakdown" role="button" href="" >Продолжить.</a>
    </article>
</div>

cars/templates/tabs/car_select_tab.html
 <div class="row">
    <article class="col-md-9 maincontent">
        <header class="page-header">
            <h4 class="page-title" style="font-size:30px" >Привет!</h4>
            <h5 class="page-title" style="font-size:24px">Для того, что бы начать поиск поломки, Вам необходимо выбрать марку, модель и год выпуска автомобиля.</h5>
        </header>
        <div class="container con1">
        <form>
          <div class="form-group">
              <label for="brand-select">Марка</label>
              <select class="brand-select form-control" id="brand-select" style="height: 45px;" data-url="{% url 'cars:cars_models' %}">
                {% for car_brand in cars_brands %}
                    <option value="{{ car_brand.id }}">{{ car_brand }}</option>
                {% endfor %}
              </select>
          </div>
          <div class="form-group">
            <label for="model-select">Модель</label>
              <select class="model-select form-control" id="model-select" style="height: 45px;" data-url="{% url 'cars:cars_years' %}">
              </select>
          </div>
          <div class="form-group">
           <label for="year-select">Год выпуска</label>
              <select class="year-select form-control" id="year-select" style="height: 45px;" data-url="{% url 'cars:cars_modifications' %}">
              </select>
          </div>
          <div class="form-group">
           <label for="modification-select">Комплектация</label>
              <select class="modification-select form-control" id="modification-select" style="height: 45px;">
             </select>
          </div>
          <div class="form-group">
              <label for="mileage">
                Пробег
              </label>
                <input type="number" placeholder="пробег" id="mileage" class="mileage form-control">
          </div>
        <a class="btn btn-action btn-general btn-car" role="button" style="" href="">Продолжить</a>
        </form>
            <br />

        </div>
    </article>
</div>

cars/templates/tabs/service_select_tab.html
<div class="row">
    <article class="col-md-9 maincontent">
        <header class="page-header">
            <h4 class="page-title" style="font-size:30px" >Почти закончили!</h4>
            <h5 class="page-title" style="font-size:24px">Вибираем сервис.</h5>
        </header>
        <div class="container" style="min-height:350px;margin-bottom:20px; ">
            <div class="row" style="margin:5px">
                <article class="col-md-6 maincontent" style="border: 3px solid #6678b1; border-radius: 10px; background-color:#FDFCFC ; padding:30px;padding-top:0px;">
                    <header class="page-header">
                        <h1 class="page-title" ><b>Поломка:</b></h1>
                        <h2 class="page-title breakdown-name"></h2>
                    </header>
                    <div class="container-fluid" style="padding-buttom:3%">
                        <table class="tab1">
                            <tbody>
                                <tr class="tab1 breakdown-description">

                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="symptoms-dest">
                        <h2>Симптомы</h2>
                        <ul>
                            <li style="font-size: 120%;font-family: 'Didact Gothic', sans-serif;font-weight:1;text-align: left;" class="symptoms">
                            </li>
                        </ul>
                    </div>
			    </article>
                <div class="container col-md-6  ">
                </div>
            </div>
        </div>
    </article>
    <div class="row services-dest" style="margin-left: 0px;">
        <div class="col-md-8">
            <h2 class="page-title"> Подходящие автосервисы</h2>
            <table>
                <thead>
                    <tr>
                        <th>Название автосервиса</th>
                        <th>Адрес</th>
                        <th>Контакты</th>
                        <th>Прайс</th>
                    </tr>
                </thead>
                <tbody class="services">
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div id="map">

            </div>
        </div>
    </div>
</div>

<script>
ymaps.ready(function () {
    myMap = new ymaps.Map('map', {
        center: [55.751574, 37.573856],
        zoom: 9
    }, {
        searchControlProvider: 'yandex#search'
    });
});
</script>