cars/urls.py
from django.conf.urls import url

from cars.views import BreakdownSearch, AjaxCarsModels, AjaxCarsModifications, AjaxBreakdowns, AjaxCarsYears, \
    AjaxBreakdown

urlpatterns = [
    url(r'^breakdown_search/$', BreakdownSearch.as_view(), name='breakdown_search'),
    url(r'^get_models/$', AjaxCarsModels.as_view(), name='cars_models'),
    url(r'^get_years/$', AjaxCarsYears.as_view(), name='cars_years'),
    url(r'^get_modifications/$', AjaxCarsModifications.as_view(), name='cars_modifications'),
    url(r'^breakdowns/$', AjaxBreakdowns.as_view(), name='breakdowns'),
    url(r'^breakdown/$', AjaxBreakdown.as_view(), name='breakdown')
]

core/urls.py
from django.conf.urls import url

from core.views import Index, About

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^about/$', About.as_view(), name='about')
]

vsepolomki/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^cars/', include('cars.urls', namespace='cars')),
    url(r'^breakdown_search/', include('breakdown_search.urls', namespace='breakdown'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import PermissionsMixin, BaseUserManager, AbstractBaseUser
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, is_active, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_superuser=is_superuser, is_active=is_active,
                           **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, is_active=None, **extra_fields):
        return self._create_user(email, password, False, False, is_active, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = u'Пользователь'
        verbose_name_plural = u'Пользователи'

    email = models.EmailField(unique=True, error_messages={
        'required': u'Обязательное поле',
        'invalid': u'Неверный email',
        'unique': u'Пользователь с такой почтой уже существует',
    })
    first_name = models.CharField(max_length=100, verbose_name=u'Имя')
    last_name = models.CharField(max_length=100, verbose_name=u'Фамилия')
    is_staff = models.BooleanField(default=False, verbose_name=u'Персонал')
    is_active = models.BooleanField(default=False, verbose_name=u'Активирован?')
    date_joined = models.DateTimeField(default=timezone.now, verbose_name=u'Дата регистрации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    object = UserManager()

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.first_name

core/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


class About(TemplateView):
    template_name = 'about.html'

core/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" style="padding-top:100px;">
        <div class="row">
            <article class="col-md-9 maincontent">
                <header class="page-header">
                    <h4 class="page-title" style="font-size:30px" >Мы открыты для ваших предложений </h4>
                    <h5 class="page-title" style="font-size:24px">info@vsepolomki.ru</h5>
                </header>
                <div class="" style="">
                    <div class="container question-class" style="margin-top:1%;">
                    </div>
                    <h4 class="page-title" style="padding-bottom:2%;color:#000; line-height: 1.5">VsePolomki.ru - веб-сайт, оптимизированный под мобильные браузеры, предоставляющий доступ к быстрому и удобному функционалу по поиску неисправностей автомобиля. Сервис предоставит пользователю быструю и качественную диагностику автомобиля посредством общения пользователя с автоматизированной системой в диалоговом режиме без прямого участия специалистов.</h4>
                </div>
            </article>
        </div>
    </div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <header id="head" style="background:#181015 url( {% static "core/img/bg_header.jpg" %}) no-repeat; background-size: cover;  text-align: right;   color:white; background-position: center top;">
        <h1 class="lead" >Ремонт автомобиля  </h1> <h1 class="lead" style="font-size:28px;">Стал проще</h1>
    </header>
	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space" style="background-color:#F2F2F2;margin:0px; padding:10px">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="h-caption"><h4><i class="fa fa-cogs"></i>Система поиска неисправностей</h4></div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="h-caption"><h4 ><i class="fa fa-car"  ></i>Подбор автосервисов</h4></div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="h-caption"><h4><i class="fa fa-wrench"></i>Инструкции по починке</h4></div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="h-caption"><h4><i class="fa fa-book"></i>База неисправностей</h4></div>
				</div>
			</div> <!-- /row  -->
		</div>
	</div>
	<div class="jumbotron top-space" style="padding:20px">
		<div class="container">
			<h5 class="text-center" style="font-size:28px;">Как это работает?</h5>
			<div class="row" >
				<div class="col-md-6 col-sm-6" style="margin-top:40px">
					<h4 class="num-list-header">1. Выберите ваш автомобиль. </h4>
					<h5 style="margin-left: 21px;">Выберите марку и модель вашего автомобиля.</h5>
					<h4 class="num-list-header" >2. Укажите вид работ.</h4>
					<h5 style="margin-left: 21px;">Расскажите нам что конкретно вам требуется починить.</h5>
					<h4 class="num-list-header" >3. Найдите подходящий автосервис</h4>
					<h5 style="margin-left: 21px;">Широкий диапазон цен, расчитанный по всем автосервисам Москвы.</h5>
				</div>

  				<div class="col-md-6 col-sm-6" align="right" style="margin-top:15px;">
  					<img class="ad2" src="{% static 'core/img/dialog.jpg' %}">
  				</div>
			</div>
		</div>
		<div class="text-center"  style="color:#F06015">
			<a class="btn btn-action btn-general" role="button" href="{% url 'cars:breakdown_search' %}" >Начать</a>
		</div>
	</div>
    <div class="jumbotron top-space" style="background-color:#F2F2F2;margin:0px;">
		<div class="container">
			<h5 class="text-center" style="font-size:28px;">VsePolomki.ru - это:</h5>
			<div class="row">
			<div class="col-md-6 col-sm-6">
				<div class="h-body">
					<h4 style="color:#555"><b>800 000</b> активных пользователей. </h4>
				</div>
			</div>
			<div class="col-md-6 col-sm-6" align="right">
				<div class="h-body">
					<h4 style="color:#555; "><b>10 000</b> автосервисов-партнеров.</h4>
				</div>
			</div>
			</div> <!-- /row  -->
			<div class="row">
			<div class="col-md-6 col-sm-6">
				<div class="h-body">
					<h4 style="color:#555"><b>120</b> поломок в базе неисправностей. </h4>
				</div>
			</div>
			<div class="col-md-6 col-sm-6" align="right">
				<div class="h-body">
					<h4 style="color:#555;"><b>1000</b> найденых поломок с нашей помощью. </h4>
				</div>
			</div>
			</div> <!-- /row  -->
		</div>
	</div>
	<div class="jumbotron top-space"  style="padding:20px">
		<div class="container">
			<h5 class="text-center" style="font-size:28px;">Как пользоваться СПН?</h5>
			<div class="row">
				<div class="col-md-6 col-sm-6" style="margin-top:40px">
					<h4 class="num-list-header">1. Выберите ваш автомобиль. </h4>
					<h5 style="margin-left: 21px;">Выберите марку и модель вашего автомобиля.</h5>
					<h4 class="num-list-header" >2. Укажите симптомы.</h4>
					<h5 style="margin-left: 21px;">Например, проваливается тормоз или не работают дворники.</h5>
					<h4 class="num-list-header" >3. Ответьте на вопросы системы поиска неисправностей</h4>
					<h5 style="margin-left: 21px;">Вопросы могут быть совсем простые или иметь подробные инструкции.</h5>
					<h4 class="num-list-header" >4. Ознакомьтесь с возможными неисправностями вашего автомобиля.</h4>
					<h5 style="margin-left: 21px;">Найдите автосервис, готовый починить конкретно такую неисправность.</h5>
				</div>
  				<div class="col-md-6 col-sm-6" align="right" style="margin-top:35px;">
					<img class="ad2" src="{% static 'core/img/chat.jpg' %}" style="max-width:360px; max-height:348px;">
  				</div>
			</div>
		</div>

		<div class="text-center"  style="color:#F06015">
			<a class="btn btn-action btn-general" role="button" href="{% url 'breakdown:breakdown_search' %}">Найти неисправность</a>
		</div>
	</div>


	<div class="jumbotron top-space"  style="background-color:#F2F2F2;padding:20px">
		<div class="container">
			<h5 class="text-center" style="margin:0px; margin-bottom:50px; font-size: 28px">Какие марки поддерживает поиск неисправностей?</h5>
			<div class="row">
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/lada.jpg' %}" width=60px></div>
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/bmw.jpg' %}" width=50px></div>
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/mercedes.jpg' %}" width=60px></div>
				<div class="clearfix hidden-lg hidden-md hidden-sm"></div>
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/mith.jpeg' %}" width=60px></div>
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/mazda.jpg' %}" width=47px></div>
				<div class="col-md-2 col-sm-2 col-xs-4"><img src="{% static 'core/img/brands/ford.jpg' %}" width=60px></div>
			</div>
		</div> <!-- /row  -->
	</div>
	<!-- /Highlights -->
{% endblock %}